spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mercadolivro
    password: mercadolivro
jwt:
  secret: d0d2be1e-7d2d-4861-91f7-4083600bcae3
  expiration: 600000