spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivroproduction?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: mercadolivro
    password: mercadolivro
jwt:
  secret: 3595e132-9553-4dea-98d8-2f48145125a1
  expiration: 300000
springfox:
    documentation:
      enabled: false
server:
  port: 8081